### ISSUE TITLE
Diacritics alignment

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#11]
The alignment of some diacritics needs to be adjusted, e.g. macron 

<img width="949" alt="Screen Shot 2021-01-26 at 15 32 35" src="https://user-images.githubusercontent.com/48698976/105925954-033c6e00-600f-11eb-94b9-031385982a88.png">

<img width="122" alt="Screen Shot 2021-01-26 at 15 31 19" src="https://user-images.githubusercontent.com/48698976/105925974-0b94a900-600f-11eb-8bf9-6708be7f0587.png">
<img width="278" alt="Screen Shot 2021-01-26 at 15 31 02" src="https://user-images.githubusercontent.com/48698976/105925990-18190180-600f-11eb-9c92-d1cbc6cf9c11.png">

**Comment by santhoshtr** [comment]
Fixed in c498245db6b3739d0156d601b180e5177f1eb97c
