### ISSUE TITLE
Designers Bio Information

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#12]
This information is intended to feed the Designers section in the [Specimen page](https://fonts.google.com/specimen/Gayathri) of each font in Google Fonts. 

This information could include one entry for SMC and another for Santhosh Thottingal, in which case the requirements would be the same for each one: bio text 100 to 250 characters length extension and a 100*100 px png image

A good reference of the bio could be [Boutros](https://github.com/google/fonts/blob/master/catalog/designers/boutrosfonts/bio.html).

**Comment by santhoshtr** [comment]
Santhosh Thottingal
---------------------------
Santhosh Thottingal is a typeface designer and a software engineer from India. He is an active contributor of Swathanthra Malayalam Computing organization and has designed popular Malayalam typefaces like Manjari and Chilanka. 

Website: https://thottingal.in
Github profile picture can be reused for profile image

SMC
------

Swathanthra Malayalam Computing (SMC) is a free software collective engaged in development, localization, standardization and popularization of various Free and Open Source Softwares in Malayalam language.

Website: https://smc.org.in
Profile image:  ![smc-logo-100x100](https://user-images.githubusercontent.com/161672/106711811-13130e00-661e-11eb-83af-e609916fbcbf.png)
