### ISSUE TITLE
Spacing changes

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#14]
New text images show some spacing changes that could lead to reflows in long text paragraphs.

The reflow is not seen when testing the fonts in Cyreal, but those are shorter paragraphs and don't include Malayalam. Please ensure the spacing is as intended.

This should be reviewed/approved by @m4rc1e and @davelab6.

-----

**OS X High Sierra Safari 11 1**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/106828770-d7496a00-6658-11eb-8928-931a8a8e788d.gif)

**Windows 10 Chrome 71 0**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/106828780-dca6b480-6658-11eb-8a3f-7d0c3873e1ce.gif)

**Windows 10 Edge 18 0**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/106828783-ddd7e180-6658-11eb-9c1e-34c9efe3dab4.gif)

**Comment by santhoshtr** [comment]
These changes looks reasonable to me. I had corrected the [bearings of digits](https://thottingal.in/blog/2020/04/11/manjari-new-version/) that cause the first line change. The second change is because of a ligature added in #2

**Comment by davelab6** [comment]
Agreed, please proceed
