### ISSUE TITLE
Manjari designers bio information

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#15]
Hi @santhoshtr,

Currently, In the designer's field of the font info, there is only you listed, Santhosh Thottingal. Nevertheless, in the AUTHORS file in the repository, there is also Kavya Manohar.

Please, confirm the names that should be credited as designers in the "About" section of the specimen and provide us with a bio text of you and Kavya, of 100 to 250 characters length extension and a 100*100 px png image.

**Comment by kavyamanohar** [comment]
@vv-monsalve ,
Here is a short bio of mine:

[Kavya Manohar](https://kavyamanohar.com/) is a language technology enthusiast and a maintainer of a couple of Malayalam fonts by Swathanthra Malayalam Computing organization.

![kavyamanohar](https://user-images.githubusercontent.com/4884477/108102529-a9c7dc00-70ae-11eb-802a-c529690f3abd.png)

**Comment by vv-monsalve** [comment]
@santhoshtr nevermind about your information, as I went back to the closed [issue](https://github.com/smc/manjari/issues/12) with it.


> Please, confirm the names that should be credited as designers in the "About" section of the specimen

Please confirm the above.

> Here is a short bio of mine:

Thanks, Kavya.

**Comment by santhoshtr** [comment]
Designer is myself. Kavya contributed in opentype engineering part. So if "About" is about designers strictly, then it is just me.

**Comment by vv-monsalve** [comment]
> Designer is myself. Kavya contributed in opentype engineering part. So if "About" is about designers strictly, then it is just me.

Regularly we list names included on the designer field in the font info (`name table ID9`) of the project, so in this case it would be you.

However, the decision on whether to include someone on the authors.txt or not is entirely within the project’s discretion, and it is commonly related to the relevance of the work done into the project.

For another type of contributions, there is the Contributors file of the project.
