### ISSUE TITLE
Diffenator Report

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#16]
New Diffenator results after pulling the latest files in the repository at commit 49041a89f20ef46255853e6f1c6073758c1cb10d and producing new fonts.

### gde base missing
![gdef_base_missing](https://user-images.githubusercontent.com/48698976/108128935-7cae0600-707b-11eb-8760-de2e8160e9e0.gif)

**Comment by vv-monsalve** [comment]
### glyphs missing
![glyphs_missing](https://user-images.githubusercontent.com/48698976/108129031-994a3e00-707b-11eb-8d1a-a1cbac1b5254.gif)

**Comment by vv-monsalve** [comment]
### glyphs modified
![glyphs_modified](https://user-images.githubusercontent.com/48698976/108129088-ab2be100-707b-11eb-8101-d58669b00729.gif)

**Comment by vv-monsalve** [comment]
### glyphs new
![glyphs_new](https://user-images.githubusercontent.com/48698976/108129183-cf87bd80-707b-11eb-8bf0-c183651037db.gif)

**Comment by vv-monsalve** [comment]
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/108129388-21304800-707c-11eb-9614-7c935fcf7c0f.gif)

**Comment by santhoshtr** [comment]
> New Diffenator results after pulling the latest files in the repository at commit [49041a8](https://github.com/smc/manjari/commit/49041a89f20ef46255853e6f1c6073758c1cb10d) and producing new fonts.
> ### gde base missing
> 
> ![gdef_base_missing](https://user-images.githubusercontent.com/48698976/108128935-7cae0600-707b-11eb-8760-de2e8160e9e0.gif)

This is as expected. The Mark Glyphs -  ് and others  - Should have zero advance width as correctly reported by fontbakery. That fix caused a small width correction. All other readjustments of position is due to this fix.

> ### glyphs modified
> 
> ![glyphs_modified](https://user-images.githubusercontent.com/48698976/108129088-ab2be100-707b-11eb-8101-d58669b00729.gif)

This is as expected. Latin Diacritic marks alignment was reviewed and corrected as you pointed out.


> ### glyphs new
> 
> ![glyphs_new](https://user-images.githubusercontent.com/48698976/108129183-cf87bd80-707b-11eb-8bf0-c183651037db.gif)

This is as expected. Added more latin glyphs as needed by Google fonts.
