### ISSUE TITLE
problem with font ligatures

### ISSUE THREAD

**Issue by nerdy-panda** [smc/manjari#3]
thank you for create this font .
i use for write codes then this font does not bother the eyes .
but i have problem in `font ligatures` in my editor .
i need this characters  >= == != <=  ->   to be displayed well . like this photo 
![image-1552751428748](https://user-images.githubusercontent.com/39291525/98072994-93d63880-1e7c-11eb-9b95-f275aad32c14.png)

please add this feature for font

**Comment by santhoshtr** [comment]
Manjari is not a font designed for coding. It is not monospace font. You may need to use fonts like https://github.com/tonsky/FiraCode for a monospace font with programming ligatures support.

Trying to add more features to Manjari beyond its purpose is not good.
