### ISSUE TITLE
Vertical Metrics Regression

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#4]
The changes reported by Diffenator on Typographic vertical metrics will generate significant regressions in Bold and Thin weights.

As per the [Spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#updating-an-existing-family) visual regressions must be avoided as much as possible, so an important change like this would need @m4rc1e confirmation.

### Attribs modified:

**Thin**
```
table               attrib              value_a             value_b             
OS/2                sTypoAscender       1400                1500                
OS/2                sTypoDescender      -800                -750 
```
**Bold**
```
table               attrib              value_a             value_b             
OS/2                sTypoDescender      -900                -750     
```
<br>

### Text comparisons
These are comparisons made using [Cyreal test page](http://www.cyreal.org/Font-Testing-Page/index.php). Only Latin can be displayed there, so you would like to perform similar images for Malayalam.

**Bold**

![Manjari-Text-Bold](https://user-images.githubusercontent.com/48698976/99737955-7073d600-2a97-11eb-8f9e-3b5ef1c04386.gif)

**Thin**

![Manjari-Text-Thin](https://user-images.githubusercontent.com/48698976/99738010-8e413b00-2a97-11eb-89d3-6d10d7ed18b4.gif)

**Comment by vv-monsalve** [comment]
### Diff Browser comparative gifs

**OS X High Sierra Safari 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/99739005-d06b7c00-2a99-11eb-9902-dc1747180c68.gif)

**Windows 10 Chrome 69**
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/99739013-d4979980-2a99-11eb-8fa3-75700518c681.gif)

**Windows 10 Firefox 62**
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/99739016-d5303000-2a99-11eb-8e7c-4d5ab230bcd2.gif)

**Comment by m4rc1e** [comment]
Vert metrics should visually match. Is fsSelection bit 7 enabled on the new fonts?

**Comment by vv-monsalve** [comment]
> Vert metrics should visually match. Is fsSelection bit 7 enabled on the new fonts?

Yes, it is enabled.

**Comment by m4rc1e** [comment]
If it's also enabled in the previous fonts as well, just set the typo metrics to the previous version. If it isn't, then you'll need to read our spec.

**Comment by vv-monsalve** [comment]
> If it's also enabled in the previous fonts as well, just set the typo metrics to the previous version.

I just had a look to the downloaded version, and it is also enabled, so the typo metrics should be changed to the previous values.

**Comment by vv-monsalve** [comment]
@santhoshtr Please change the typo metrics to the previous values:

**Thin**
```      
sTypoAscender       1400                
sTypoDescender      -800 
```
**Bold**
```         
sTypoDescender      -900    
```

**Comment by santhoshtr** [comment]
Hi, vertical metrics for Thin and Bold were corrected in commit 0a75d10ef024010dd1b1cbe79b53f1793976837e because the values were not matching with Regular. This issue was spotted by Fontbakery as follows:

```
 >> com.google.fonts/check/family/vertical_metrics
    Each font in a family must have the same set of vertical metrics values.
    

      Rationale:                                                                
      We want all fonts within a family to have the same vertical metrics so    
      their line spacing is consistent across the family.                       

    * FAIL: sTypoAscender is not the same across the family:
Manjari Bold: 1500
Manjari Regular: 1500
Manjari Thin: 1400 [code: sTypoAscender-mismatch]
    * FAIL: sTypoDescender is not the same across the family:
Manjari Bold: -900
Manjari Regular: -750
Manjari Thin: -800 [code: sTypoDescender-mismatch]
    * FAIL: ascent is not the same across the family:
Manjari Bold: 1500
Manjari Regular: 1500
Manjari Thin: 1400 [code: ascent-mismatch]
    * FAIL: descent is not the same across the family:
Manjari Bold: -900
Manjari Regular: -750
Manjari Thin: -800 [code: descent-mismatch]


    Result: FAIL
```

So, the change you see is the effect of this bug fix. This issue was pointed out when Lasse Fister was trying to update fonts. With this fix new releases were done. 

To avoid visual change in new versions, if we revert that commit, the vertical metrics mismatch test fail.

What do you advice?

**Comment by vv-monsalve** [comment]
> This issue was spotted by Fontbakery as follows:

Yes, it's reported and required in FontBakery according to our [Specification on vertical metrics](https://github.com/googlefonts/gf-docs/tree/master/VerticalMetrics). Nevertheless, in [update](https://github.com/googlefonts/gf-docs/tree/master/Spec#qa) cases, some exceptions may apply as the main focus becomes to avoid visual regressions respecting the served fonts to avoid breaking the sites that already are using the fonts.

> To avoid visual change in new versions, if we revert that commit, the vertical metrics mismatch test fail.

Thus that is why in this case the previous values are required despite the fail that FB will report, we'll let it pass.

**Comment by vv-monsalve** [comment]
@santhoshtr Please let me know once the fix has been done so that we can continue with the process

**Comment by santhoshtr** [comment]
Reverted the change in 832e54e396dd77a148b1bc782a37f828d08b65e5 and added an exclusion for the check in 05a899d
