### ISSUE TITLE
Diffenator Results

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#5]
### Diffenator Results

These are the resulting comparative giffs for GDEF, Glyphs modified and new.
The images display Regular as a sample.

**gdef base new**
![gdef_base_new](https://user-images.githubusercontent.com/48698976/99731649-36510700-2a8c-11eb-9991-a715a451a2c5.gif)
**glyphs modified**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/99731654-36e99d80-2a8c-11eb-8293-27556502eb0f.gif)
**glyphs new**
![glyphs_new](https://user-images.githubusercontent.com/48698976/99731656-37823400-2a8c-11eb-979f-b427729a2ac5.gif)

**Comment by santhoshtr** [comment]
Yes, these were the modification as documented in changelog https://gitlab.com/smc/fonts/manjari/-/releases

The first one is a recently added character in last release of unicode. 

I am wondering do you see this an "issue" or an observation?

**Comment by vv-monsalve** [comment]
> I am wondering do you see this an "issue" or an observation?

This is just as an observation so that designers can inspect everything is as expected or if there is something unexpected reported.

In this case particularly about the GDEF change, as it is also [WARNS reported](https://github.com/smc/manjari/issues/9) about the same table that could be related.

**Comment by vv-monsalve** [comment]
New Diffenator reports after pulling latest files in the repository at commit 05a899d1a4564d6b48bcda8c853eb8e4519a2186 and producing new fonts.

Please review them and ensure everything is working as espected.

### Glyphs Modified

**Bold**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106827865-360de400-6657-11eb-8b9a-a567e071bc67.gif)

**Regular**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106827891-445c0000-6657-11eb-994e-2d8f4ee87e4d.gif)

**Thin**
![glyphs_modified](https://user-images.githubusercontent.com/48698976/106827927-53db4900-6657-11eb-9e73-302cb839d008.gif)

**Comment by vv-monsalve** [comment]
### Glyphs New

**Bold**
![glyphs_new](https://user-images.githubusercontent.com/48698976/106828135-8e44e600-6657-11eb-9916-223a56a5c625.gif)

**Regular**
![glyphs_new](https://user-images.githubusercontent.com/48698976/106828150-9735b780-6657-11eb-8998-b96d6008e667.gif)

**Thin**
![glyphs_new](https://user-images.githubusercontent.com/48698976/106828170-a3ba1000-6657-11eb-9c93-95664bc54d82.gif)
