### ISSUE TITLE
Reported Fails 

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#8]
These are the reported Fails after pulling the latest files int the repo at commit e04cf2955769ad8356264bd0792b456aec4d9e10 "Remove unused designspace file"

<details>
<summary>🔥 <b>FAIL:</b> Check copyright namerecords match license file.</summary>

* [com.google.fonts/check/name/license](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license)
<pre>--- Rationale ---

A known licensing description must be provided in the NameID 14 (LICENSE
DESCRIPTION) entries of the name table.

The source of truth for this check (to determine which license is in use) is a
file placed side-by-side to your font project including the licensing terms.

Depending on the chosen license, one of the following string snippets is
expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of the name
table:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;

Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.

When in doubt, please choose OFL for new font projects.

</pre>

* 🔥 **FAIL** License file LICENSE.txt exists but NameID 13 (LICENSE DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that. Value was: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL" Must be changed to "Licensed under the Apache License, Version 2.0" [code: wrong]

</details>

The License.txt should be renamed to OFL.txt, otherwise, it would be interpreted as an Apache License.

**Comment by vv-monsalve** [comment]
<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components.</summary>

* [com.google.fonts/check/glyf_nested_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/glyf_nested_components)
<pre>--- Rationale ---

There have been bugs rendering variable fonts with nested components.
Additionally, some static fonts with nested components have been reported to
have rendering and printing issues.

For more info, see:
* https://github.com/googlefonts/fontbakery/issues/2961
* https://github.com/arrowtype/recursive/issues/412


</pre>

* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* k1l1
	* k1l3u1
	* k1l3u2
	* k3l3u1
	* k3l3u2
	* t3u1
	* t3u2
	* th1l3u1
	* th1l3u2
	* p1l3u1 and 70 more. [code: found-nested-components]

</details>

There is a newly implemented flag in fontmake `-f` to flatten components, that could help to solve this Fail.

**Comment by santhoshtr** [comment]
> FAIL: Check copyright namerecords match license file.

Fixed in a483e86c8e40397d5c0fabdc32f236738ac9dd73

> FAIL: Check glyphs do not have components which are themselves components.

Fixed in 6fe9b35d85b5f6da4c095de4b676798040cfca28
